name: furni_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  google_fonts: ^6.3.3

  flutter_carousel_widget: ^2.2.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/shopping-bag.png  
      - assets/images/logo.svg
      - assets/images/furniLogo.svg
      - assets/images/sofa2.png
      - assets/images/welcome.png
      - assets/images/login.png
      - assets/images/profile_picture.jpg
      - assets/images/camera_icon.svg
      - assets/images/shopping-bag.png
      - assets/images/furniLogo.svg
      - assets/images/carousel1.png
      - assets/images/carousel2.png
      - assets/images/carousel3.png
      - assets/images/living_room.png
      - assets/images/bedroom.png
      - assets/images/kitchen1.svg
      - assets/images/kitchen0.png
      - assets/images/about_us.png
      - assets/images/cart_logo.svg
      - assets/images/user-circle.svg
      - assets/images/shop-page.svg
      - assets/images/sofa.png
      - assets/images/product_image_1.jpg
      - assets/images/product_image_2.jpg
      - assets/images/product_image_3.jpg
      - assets/images/product_image_5.jpg
      - assets/images/Left_arrow.png
      - assets/images/Right_arrow.png
      - assets/images/product_image_4.png
      - assets/images/shopping_bag.svg
      - assets/images/user-circle.svg
      - assets/images/person1.png
      - assets/images/person2.png
      - assets/images/person3.png
      - assets/images/store.svg
      - assets/images/mail.svg
      - assets/images/Map.png
      - assets/images/phone.svg
      - assets/images/Subtract.svg
      - assets/images/img1.png
      - assets/images/search.svg
      - assets/images/a40cc85f069a0857fe7da4976ba73bf5db64a055.jpg
      - assets/images/sofa.png
      - assets/images/Dining table.png
      - assets/images/Celebration.png

     
    - assets/images/shopping-bag.png
    - assets/images/logo_furni.svg
    - assets/images/furniLogo.svg
    - assets/images/carousel1.png
    - assets/images/carousel2.png
    - assets/images/carousel3.png
    - assets/images/living_room.png
    - assets/images/bedroom.png
    - assets/images/kitchen1.svg
    - assets/images/kitchen0.png
    - assets/images/about_us.png
    - assets/images/cart_logo.svg
    - assets/images/user-circle.svg
    - assets/images/shop-page.svg
    - assets/images/home2.svg
    - assets/images/product_image_1.jpg
    - assets/images/product_image_2.jpg
    - assets/images/product_image_3.jpg
    - assets/images/product_image_5.jpg
    - assets/images/Left_arrow.png
    - assets/images/Right_arrow.png
    - assets/images/product_image_4.png
    - assets/images/shopping_bag.svg
    - assets/images/person1.png
    - assets/images/person2.png
    - assets/images/person3.png
    - assets/images/store.svg
    - assets/images/mail.svg
    - assets/images/Map.png
    - assets/images/phone.svg
    - assets/images/Subtract.svg
    - assets/images/img1.png
    - assets/images/search.svg
    - assets/images/a40cc85f069a0857fe7da4976ba73bf5db64a055.jpg
    - assets/images/sofa.png
    - assets/images/Dining table.png
    - assets/images/Celebration.png
    - assets/images/delivery.svg
    - assets/images/money.svg
    - assets/images/lock.svg
    - assets/images/call.svg
    - assets/images/filter.svg
    - assets/images/shop_hero_section.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
   